### ISSUE TITLE
Change .txt file extensions to .asc

### ISSUE THREAD

**Issue by timrae** [ankidroid/ankidroiddocs#22]
If we change all of the .txt files to .asc files then github can automatically render them with asciidoctor, which would be extremely useful as that way edits via the github website can be viewed live on the "Preview" tab.

@agrueneberg would the pipeline need to be modified to support such a change?

**Comment by agrueneberg** [comment]
Yes, the pipeline only converted `.txt` files. I have changed this to `.asc`.

**Comment by timrae** [comment]
Excellent, thanks! That makes it so much easier to edit the files.

**Comment by agrueneberg** [comment]
Yes, looks much better! Let me know if you run into any issues, the pipeline is kind of tricky to test.
