### ISSUE TITLE
Rename "Action bar" to "App bar"

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/ankidroiddocs#28]
according to this topic:
_Unification of terminology: "Action bar" and "Tool bar"_
_https://github.com/ankidroid/Anki-Android/issues/4230_

**Comment by nlok5923** [comment]
@snowtimeglass please can you assign me this issue.

**Comment by DevAStar08** [comment]
Please have a glance on the changes I have made for issue no .#28 . Thank you.
![changes](https://user-images.githubusercontent.com/72031540/111029577-62b9d600-8423-11eb-9707-212443940bbf.PNG)

**Comment by mikehardy** [comment]
@StarTrooper08 if you propose a PR we can consider and merge it - thank you!
https://github.com/ankidroid/ankidroiddocs/pulls

**Comment by StarTrooper08** [comment]
I have made new PR for issue no #28. Have I done it alright or need some changes to be made??
Do reply for the same !!

**Comment by david-allison-1** [comment]
> I have made new PR for issue no #28. Have I done it alright or need some changes to be made??
> Do reply for the same !!

If you include `Fixes #28` in your PR description, then the linked issue will be closed when the PR is.
