### ISSUE TITLE
innerHTML and tts

### ISSUE THREAD

**Issue by isotestardo** [ankidroid/ankidroiddocs#42]
I'm using javascript to modify some fields and then publish them. I would like to make them available for the tts , using the tags, but it doesn't work. any suggestion?
Here is an example

var content = "{{Front}}";
content = content.replace(/.+?(?=\(e.g.)/,  '  ');
document.getElementById("demo").innerHTML = content;

**Comment by timrae** [comment]
No idea sorry, and this issue tracker is only for issues related to the AnkiDroid manual. You can try asking on the user forum, but note in general that we don't provide support for JavaScript.
