### ISSUE TITLE
[2.13] Explain "Set Language Hint" feature

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/ankidroiddocs#66]

**Comment by mikehardy** [comment]
I'm scanning the ankidroiddocs issues list and it looks like this is still pending but was for 2.13 I think :-)

**Comment by avinashbest** [comment]
Is anyone working on this? Or You may assign me?

**Comment by avinashbest** [comment]
- Any hint you would like to give? any format or something?
- Or I should Explain the setting of the language

**Comment by david-allison-1** [comment]
Primarily explain what the functionality does, and in the contexts where it will be useful (bilingual cards)

Additional context to the change:

https://github.com/ankidroid/Anki-Android/issues/3496

https://www.youtube.com/watch?v=JrxDjTrRhBE

https://github.com/ankidroid/Anki-Android/pull/6416

**Comment by avinashbest** [comment]
Created a pull request for the Set Language Hint feature (docs) 
https://github.com/ankidroid/ankidroiddocs/pull/89
