### ISSUE TITLE
Add docs for new keyboard shortcuts

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/ankidroiddocs#71]
Needs documenting in https://github.com/ankidroid/ankidroiddocs

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/pull/7197#issuecomment-695870732_

**Comment by david-allison-1** [comment]
I'll do this after the follow-up to add the remaining shortcuts

**Comment by mikehardy** [comment]
Done with #77 I think
