### ISSUE TITLE
ankidroid.org nginx dies on the first day of the month

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/ankidroiddocs#74]
Placeholder to explain workarounds/issue triage

**Comment by mikehardy** [comment]
* probably something to do with logrotate monthly not restarting it but initial investigation yielded no results
* could be handled by a cron job that checks if it is up and does `service nginx restart` if not - that restart is very fast, is idempotent (so it is safe to run) and the cron should be lightweight enough to run hourly even as a stopgap

Note that access to the server is restricted to those that have the SSH key for user `ankidroid@ankidroid.org` - I have it but it has not been distributed to others so unless I/we do that, I own this :sweat_smile: - which is fine either way

**Comment by mikehardy** [comment]
and just like that it stopped stopping 🤷
