### ISSUE TITLE
Investigate LetsEncrypt cert on < Android 7.1

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/ankidroiddocs#79]
I'm not familiar with this matter. Needs investigation. Emphasis mine.

https://www.androidpolice.com/2020/11/07/many-websites-will-stop-working-on-older-android-versions-in-2021/

https://letsencrypt.org/2019/04/15/transitioning-to-isrg-root.html

> Due to concerns about insufficient ISRG root propagation on Android devices we have decided to move the date on which we will start serving a chain to our own root to January 11, 2021. We had originally delayed this change until September 29, 2020.

https://community.letsencrypt.org/t/transition-to-isrgs-root-delayed-until-jan-11-2021/125516

> Currently Let’s Encrypt certificates are trusted on older devices by virtue of our cross-signature from IdenTrust’s DST Root X3. That cross-signature expires March 17 2021. We plan to generate new intermediate certificates and get cross-signatures on them, but those cross-signatures will only be good until September 30 2021 at the latest. That’s when DST Root X3 itself expires.

> After September 30 2021, Let’s Encrypt certificates won’t work on Android devices older than 7.1. So why not wait until then to change which root we recommend chaining to? We don’t expect the Android situation to change much in the coming year, which means **sites that need support for older Android devices may need to switch CAs**. We’d like to give those sites plenty of time to transition. But some of those sites probably won’t be aware of the need to transition until they start receiving reports of errors from their users. In 2020, the fix for such errors will be simple: The site can change which intermediate it serves in its certificate chain, and everything will work fine for another year. However, if a site doesn’t receive error reports until September 2021, it would be stuck with no quick fix and needing to change CAs entirely during an outage. That’s not good for anyone.

**Comment by mikehardy** [comment]
For Android < 7.1 where the vendor has not shipped an updated root cert store there is nothing we can actually do.

But: https://community.letsencrypt.org/t/transition-to-isrgs-root-delayed-until-jan-11-2021/125516

> Also, it’s worth noting that affected Android users will have the option of installing Firefox, which supports Android 4.1 and above 26. Firefox ships its own root store 46, which includes ISRG Root X1.

So the recommendation should be "install Firefox and set as default browser"

I think this is actually the only action within our sphere of control

**Comment by david-allison-1** [comment]
No action should be necessary: https://letsencrypt.org/2020/12/21/extending-android-compatibility.html

I believe we can close this, leaving for a second look over
